import { DashboardDefinition } from "./dashboard";
import { ReportDefinition } from "./report";

type Sys = Omit<ReportDefinition, "system">;

/**
 * Relatórios prontos. Cada um é só uma consulta salva sobre o catálogo: um
 * relatório novo aqui não precisa de rota nem de tela. A categoria segue o tema.
 */
const REPORTS: Sys[] = [
  // ── Operação ──────────────────────────────────────────────────────────────
  {
    id: "sys-os-situacao",
    name: "OS por situação",
    description: "Quantas OS estão pendentes, em andamento, concluídas e canceladas.",
    category: "Operação",
    visualization: "pie",
    spec: { dataset: "service_orders", dimensions: ["status"], measures: ["order_count"] },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-os-prazo",
    name: "Prazos das OS",
    description: "Em aberto no prazo ou atrasadas; concluídas no prazo ou com atraso.",
    category: "Operação",
    visualization: "bar",
    spec: { dataset: "service_orders", dimensions: ["deadline"], measures: ["order_count"] },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-os-tipo",
    name: "OS por tipo de serviço",
    description: "Volume, conclusão, atraso e tempo até concluir, por tipo de serviço.",
    category: "Operação",
    visualization: "table",
    spec: {
      dataset: "service_orders",
      dimensions: ["type_service"],
      measures: ["order_count", "concluded_count", "completion_rate", "overdue_count", "avg_completion_days"],
      order: [["order_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-os-time",
    name: "Desempenho por time",
    description: "OS enviadas a cada time, conclusão e cumprimento de prazo.",
    category: "Operação",
    visualization: "hbar",
    spec: {
      dataset: "service_orders",
      dimensions: ["team"],
      measures: ["order_count", "concluded_count", "completion_rate", "on_time_rate"],
      order: [["order_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-os-evolucao",
    name: "Abertura e conclusão de OS",
    description: "OS abertas e concluídas por semana.",
    category: "Operação",
    visualization: "line",
    spec: {
      dataset: "service_orders",
      measures: ["order_count", "concluded_count"],
      timeDimension: { dimension: "created", granularity: "week" },
    },
    defaultPeriod: "last_quarter",
  },
  {
    id: "sys-aceite",
    name: "Aceite de OS por pessoa",
    description: "OS recebidas, aceitas e recusadas, e o tempo de resposta de cada pessoa.",
    category: "Operação",
    visualization: "table",
    spec: {
      dataset: "assignments",
      dimensions: ["person"],
      measures: ["sent_count", "accepted_count", "declined_count", "waiting_count", "acceptance_rate", "avg_response_minutes"],
      order: [["sent_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-recusas",
    name: "Motivos de recusa de OS",
    description: "Por que as OS foram recusadas.",
    category: "Operação",
    visualization: "hbar",
    spec: {
      dataset: "assignments",
      dimensions: ["decline_reason"],
      measures: ["declined_count"],
      filters: [{ dimension: "acceptance", operator: "equals", values: ["RECUSADA"] }],
      order: [["declined_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-execucoes",
    name: "Qualidade das execuções",
    description: "Aprovação de primeira, ajustes pedidos, tempo até avaliar e fotos por executor.",
    category: "Operação",
    visualization: "table",
    spec: {
      dataset: "executions",
      dimensions: ["executor"],
      measures: ["exec_count", "approved_count", "rework_count", "approval_rate", "avg_review_hours", "avg_photos"],
      order: [["exec_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-cerca",
    name: "Saídas da cerca por pessoa",
    description: "Quem saiu do local da OS durante o serviço, quantas vezes e a que distância.",
    category: "Operação",
    visualization: "hbar",
    spec: {
      dataset: "fence_events",
      dimensions: ["person"],
      measures: ["exit_count", "order_count", "avg_distance", "unseen_exit_count"],
      order: [["exit_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-cerca-local",
    name: "Saídas do local de ponto",
    description: "Quem saiu do local de ponto durante a jornada, quantas vezes, quanto se afastou e se o gestor foi avisado.",
    category: "Pessoas",
    visualization: "hbar",
    spec: {
      dataset: "site_fence_events",
      dimensions: ["person"],
      measures: ["exit_count", "site_count", "avg_distance", "alerted_exit_count", "unseen_exit_count"],
      order: [["exit_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-pops",
    name: "POPs mais usados",
    description: "Procedimentos aplicados nas OS e quanto delas foi concluído.",
    category: "Operação",
    visualization: "hbar",
    spec: {
      dataset: "pop_usage",
      dimensions: ["pop"],
      measures: ["order_count", "completion_rate"],
      order: [["order_count", "desc"]],
    },
    defaultPeriod: "last_quarter",
  },

  // ── Pessoas ───────────────────────────────────────────────────────────────
  {
    id: "sys-jornada",
    name: "Frequência e jornada",
    description: "Dias trabalhados, horas, média diária e horas acima da jornada por pessoa.",
    category: "Pessoas",
    visualization: "table",
    spec: {
      dataset: "work_days",
      dimensions: ["person"],
      measures: ["days_worked", "worked_hours", "avg_daily_hours", "overtime_hours"],
      order: [["worked_hours", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-horas-extras",
    name: "Horas acima da jornada",
    description: "Quem trabalhou além da jornada diária padrão, em horas e em dias.",
    category: "Pessoas",
    visualization: "hbar",
    spec: {
      dataset: "work_days",
      dimensions: ["person"],
      measures: ["overtime_hours", "overtime_days"],
      order: [["overtime_hours", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-espelho",
    name: "Espelho de ponto",
    description: "Um dia por linha: primeira entrada, última saída, períodos e horas de cada pessoa.",
    category: "Pessoas",
    visualization: "table",
    spec: {
      dataset: "work_days",
      dimensions: ["person", "day"],
      measures: ["first_in", "last_out", "sessions", "worked_hours", "overtime_hours"],
      order: [
        ["person", "asc"],
        ["day", "asc"],
      ],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-assiduidade",
    name: "Assiduidade x escala",
    description: "Dias de escala, presenças, faltas, faltas abonadas, atrasos e saídas antecipadas de cada pessoa.",
    category: "Pessoas",
    visualization: "table",
    spec: {
      dataset: "attendance",
      dimensions: ["person"],
      measures: [
        "scheduled_days",
        "present_days",
        "absent_days",
        "excused_days",
        "late_days",
        "late_minutes",
        "early_leave_days",
        "early_leave_minutes",
        "attendance_rate",
        "punctuality_rate",
      ],
      order: [["absent_days", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-faltas-dia",
    name: "Faltas e atrasos por dia",
    description: "Faltas, faltas abonadas, atrasos e saídas antecipadas contra a escala, dia a dia.",
    category: "Pessoas",
    visualization: "bar",
    spec: {
      dataset: "attendance",
      measures: ["absent_days", "excused_days", "late_days", "early_leave_days"],
      timeDimension: { dimension: "day", granularity: "day" },
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-abonos",
    name: "Ausências e abonos",
    description: "Pedidos de abono por tipo: aprovados, rejeitados, pendentes e dias abonados.",
    category: "Pessoas",
    visualization: "table",
    spec: {
      dataset: "absences",
      dimensions: ["type"],
      measures: ["request_count", "approved_count", "rejected_count", "pending_count", "approved_days"],
      order: [["request_count", "desc"]],
    },
    defaultPeriod: "last_quarter",
  },
  {
    id: "sys-status-agora",
    name: "Status da equipe agora",
    description: "Pessoas ativas disponíveis, ausentes e offline neste momento.",
    category: "Pessoas",
    visualization: "pie",
    spec: {
      dataset: "people",
      dimensions: ["presence"],
      measures: ["people_count"],
      filters: [{ dimension: "active", operator: "equals", values: [true] }],
    },
    defaultPeriod: null,
  },

  // ── Conformidade ──────────────────────────────────────────────────────────
  {
    id: "sys-marcacoes",
    name: "Auditoria de marcações",
    description: "Marcações ajustadas ou invalidadas, com horário original, autor e justificativa.",
    category: "Conformidade",
    visualization: "table",
    spec: {
      dataset: "time_entries",
      dimensions: ["timestamp", "person", "status", "original", "adjusted_by", "reason"],
      measures: ["entry_count"],
      filters: [{ dimension: "status", operator: "equals", values: ["ADJUSTED", "INVALIDATED"] }],
      order: [["timestamp", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-origem",
    name: "Origem das marcações",
    description: "Marcações por origem (app, manual, facial) e quanto de cada uma foi alterado.",
    category: "Conformidade",
    visualization: "bar",
    spec: {
      dataset: "time_entries",
      dimensions: ["source"],
      measures: ["entry_count", "people_count", "changed_count", "change_rate"],
      order: [["entry_count", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-inconsistencias",
    name: "Marcações inconsistentes",
    description:
      "Marcações gravadas fora da regra (entrada repetida, saída sem entrada, fora de ordem…): o ponto não recusa marcação, o gestor trata.",
    category: "Conformidade",
    visualization: "table",
    spec: {
      dataset: "time_entries",
      dimensions: ["timestamp", "person", "type", "inconsistency_reasons", "inconsistency_status", "status", "reason"],
      measures: ["entry_count"],
      filters: [{ dimension: "inconsistency_status", operator: "notEquals", values: ["NONE"] }],
      order: [["timestamp", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-offline",
    name: "Batidas feitas sem internet",
    description: "Marcações feitas no app sem conexão: horário da batida, quando chegou ao servidor e a origem.",
    category: "Conformidade",
    visualization: "table",
    spec: {
      dataset: "time_entries",
      dimensions: ["timestamp", "received", "person", "type", "source", "status"],
      measures: ["entry_count"],
      filters: [{ dimension: "offline", operator: "equals", values: [true] }],
      order: [["timestamp", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-fora-do-local",
    name: "Batidas fora do local de ponto",
    description: "Marcações feitas fora do perímetro do local de ponto da pessoa, com a distância e as coordenadas.",
    category: "Conformidade",
    visualization: "table",
    spec: {
      dataset: "time_entries",
      dimensions: ["timestamp", "person", "type", "site", "site_distance", "coordinates"],
      measures: ["entry_count"],
      filters: [{ dimension: "site_check", operator: "equals", values: ["OUTSIDE"] }],
      order: [["timestamp", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-tentativas",
    name: "Tentativas de ponto recusadas",
    description: "Por que o ponto foi recusado (fora do perímetro, rosto não confere...).",
    category: "Conformidade",
    visualization: "hbar",
    spec: {
      dataset: "clock_attempts",
      dimensions: ["reason"],
      measures: ["refused_count", "people_count"],
      filters: [{ dimension: "accepted", operator: "equals", values: [false] }],
      order: [["refused_count", "desc"]],
    },
    defaultPeriod: "this_month",
  },
  {
    id: "sys-alteracoes",
    name: "Alterações no sistema",
    description: "O que foi criado, alterado ou excluído, e por quem.",
    category: "Conformidade",
    visualization: "table",
    spec: {
      dataset: "audit",
      dimensions: ["actor", "entity", "action"],
      measures: ["change_count"],
      order: [["change_count", "desc"]],
    },
    defaultPeriod: "last_30_days",
  },
  {
    id: "sys-acessos",
    name: "Acessos por dia",
    description: "Logins e logins recusados, dia a dia.",
    category: "Conformidade",
    visualization: "line",
    spec: {
      dataset: "access",
      measures: ["login_count", "failure_count"],
      timeDimension: { dimension: "created", granularity: "day" },
    },
    defaultPeriod: "last_30_days",
  },

  // ── Contratos ─────────────────────────────────────────────────────────────
  {
    id: "sys-carteira",
    name: "Carteira de contratos",
    description: "Contratos por órgão, vigência, término e valor.",
    category: "Contratos",
    visualization: "table",
    spec: {
      dataset: "contracts",
      dimensions: ["number", "org", "validity", "end"],
      measures: ["total_value"],
      order: [["end", "asc"]],
    },
    defaultPeriod: null,
  },
  {
    id: "sys-vigencia",
    name: "Vigência dos contratos",
    description: "Contratos vigentes, vencendo em 90 dias, vencidos e inativos, com o valor.",
    category: "Contratos",
    visualization: "pie",
    spec: { dataset: "contracts", dimensions: ["validity"], measures: ["contract_count", "total_value"] },
    defaultPeriod: null,
  },
  {
    id: "sys-licitacoes",
    name: "Licitações por modalidade",
    description: "Licitações abertas e finalizadas, valor estimado e valor contratado, por modalidade.",
    category: "Contratos",
    visualization: "table",
    spec: {
      dataset: "licits",
      dimensions: ["modality"],
      measures: ["licit_count", "open_count", "total_estimated", "contracted_value"],
      order: [["licit_count", "desc"]],
    },
    defaultPeriod: null,
  },
];

export const SYSTEM_REPORTS: ReportDefinition[] = REPORTS.map((r) => ({ ...r, system: true }));

export const SYSTEM_DASHBOARDS: DashboardDefinition[] = [
  {
    id: "sys-dash-operacao",
    system: true,
    name: "Visão geral da operação",
    description: "OS, prazos, aceite, qualidade das execuções e saídas da cerca.",
    defaultPeriod: "last_30_days",
    widgets: [
      { id: "w1", reportId: "sys-os-tipo", visualization: "kpi", size: "full", title: "Ordens de serviço" },
      { id: "w2", reportId: "sys-os-evolucao", size: "lg" },
      { id: "w3", reportId: "sys-os-situacao", size: "sm" },
      { id: "w4", reportId: "sys-os-prazo", size: "md" },
      { id: "w5", reportId: "sys-os-time", size: "md" },
      { id: "w6", reportId: "sys-aceite", visualization: "kpi", size: "full", title: "Envios e aceite" },
      { id: "w7", reportId: "sys-execucoes", visualization: "hbar", size: "md" },
      { id: "w8", reportId: "sys-cerca", size: "md" },
    ],
  },
  {
    id: "sys-dash-pessoas",
    system: true,
    name: "Pessoas e ponto",
    description: "Assiduidade contra a escala, jornada, horas extras, abonos e status da equipe.",
    defaultPeriod: "this_month",
    widgets: [
      { id: "w1", reportId: "sys-assiduidade", visualization: "kpi", size: "full", title: "Assiduidade" },
      { id: "w2", reportId: "sys-faltas-dia", size: "lg" },
      { id: "w3", reportId: "sys-status-agora", size: "sm" },
      { id: "w4", reportId: "sys-horas-extras", size: "md" },
      { id: "w5", reportId: "sys-abonos", visualization: "bar", size: "md" },
    ],
  },
];
